export const SCREEN_KEYS = {
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
  PREFERENCE_SELECTION_SCREEN: 'PREFERENCE_SELECTION_SCREEN',
};
